# .streamlit/secrets.toml
GOOGLE_API_KEY = "AIzaSyC2ZqDBmwdg7asdX9vFnoCTCCsF731zxwA"

SUPABASE_URL = "https://kuhkpduymfxycoyelvzu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1aGtwZHV5bWZ4eWNveWVsdnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDYzOTIsImV4cCI6MjA2ODQ4MjM5Mn0.xooP1HGqXyOzaOrRTF5vXPAow-IqgSDqSisYIzeSOtI" # This is your 'anon public' key


